CREATE TABLE public.user_roles (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  role text not null check (role in ('admin', 'user')),
  unique(user_id)
);

ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- Admins can manage roles, users can only read their own
CREATE POLICY "Users can read own role" ON public.user_roles
  FOR SELECT USING (auth.uid() = user_id);
  
CREATE POLICY "Admins can manage roles" ON public.user_roles
  FOR ALL USING (auth.jwt()->'app_metadata'->>'role' = 'admin');

-- Function to sync role to app_metadata
CREATE OR REPLACE FUNCTION public.sync_role_to_app_metadata()
RETURNS trigger AS $$
BEGIN
  UPDATE auth.users
  SET raw_app_meta_data = 
    raw_app_meta_data || 
    json_build_object('role', NEW.role)::jsonb
  WHERE id = NEW.user_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_user_role_updated
  AFTER INSERT OR UPDATE ON public.user_roles
  FOR EACH ROW EXECUTE PROCEDURE public.sync_role_to_app_metadata();
